### ISSUE TITLE
Bug or by designed ? Sidebars don't stick on main page, but on "detailed" page only?

### ISSUE THREAD

**Issue by techhubhub** [hbstack/theme-cards#131]
For example, Sidebars doesn't stick well on https://theme-cards.hbstack.dev (it kind of works)
but on stick well on https://theme-cards.hbstack.dev/blog/2023/11/diagrams-and-charts/
it should keep the same consistence.

**Comment by razonyang** [comment]
It's expected, the sidebar will be sticky until reaching the footer, same as detail pages.

**Comment by razonyang** [comment]
Cloud you please provide full screenshot, OS and browser (version)?

**Comment by techhubhub** [comment]
Google Chrome
Version 121.0.6167.85 (Official Build) (x86_64)
<img width="1920" alt="1" src="https://github.com/hbstack/theme-cards/assets/158099291/5ef838b7-8413-4cbd-b1db-672e0051e903">


<img width="1920" alt="2" src="https://github.com/hbstack/theme-cards/assets/158099291/758652af-78d4-43e9-a738-c597c7680f82">

<img width="1920" alt="3" src="https://github.com/hbstack/theme-cards/assets/158099291/1abb71fa-22a7-4753-a5b7-5129b9fc0e83">

**Comment by razonyang** [comment]
The first screenshot already reached the footer (not the page end), so I am closing this.
![image](https://github.com/hbstack/theme-cards/assets/17720932/4834c7aa-f590-43fc-af4f-553907e5cfad)

**Comment by LITUATUI** [comment]
Following the discussion #265 can you reopen this issue? Thanks!

**Comment by LITUATUI** [comment]
The problem here is that the sidebar widgets aren't scrolling down until the foot, which makes the sidebar partly hidden, even when there's space to show it fully.

![PushEVs_sidebar2](https://github.com/hbstack/theme-cards/assets/49299328/fe371159-4a2b-46b4-9bfd-ca805817291e)

However, the sidebar seems to be working as it should on the [demonstration site](https://theme-cards.hbstack.dev/blog/2023/11/diagrams-and-charts/). No empty space at the bottom of the sidebar.

**Comment by LITUATUI** [comment]
I noticed that if I add more things to the sidebar, for example another banner, the sidebar will have all its vertical space utilized and then scroll down till the footer as it should.

![PushEVs_OK](https://github.com/hbstack/theme-cards/assets/49299328/92e2b1be-1142-4fca-a04e-7d7a7c6942da)

But then we get that ugly scrollbar for the sidebar.

**Comment by razonyang** [comment]
The main reason I don't think it's worth is that, the user __doesn't focus on (care about)__ the sidebar when they already reached the footer. There are some popular sites do the same. For example,

- https://developer.mozilla.org/en-US/docs/Glossary/Void_element
- https://www.docsy.dev/docs/get-started/

> However, the sidebar seems to be working as it should on the [demonstration site](https://theme-cards.hbstack.dev/blog/2023/11/diagrams-and-charts/). No empty space at the bottom of the sidebar.

That's because there has enough content to take full height of sidebar, there will be always empty space if you don't have enough content.

> But then we get that ugly scrollbar for the sidebar.

I didn't get the _ugly_, if you mean the gap between of the ad and sidebar, then it should be a duty of the ad block, you can assign  a `margin` or `padding` to the ad block.

**Decision**

Although I don't think it would be useful, I'll provide a module to achieve that, since **Flexible and Customizable** is one of this framework's features and goals.

**Comment by LITUATUI** [comment]
When the visitor reached the footer, I prefer to give him options to either leave by clicking an affiliate banner or stay by reading another article. That's why a visible sidebar with its widgets is a most.

Do you think that adding [this](https://abouolia.github.io/sticky-sidebar/) npm package to the theme dependencies is useful?

**Comment by razonyang** [comment]
> Do you think that adding [this](https://abouolia.github.io/sticky-sidebar/) npm package to the theme's dependencies is useful? Or [this](https://github.com/kovart/sticksy) for individual widgets?

I don't know, but I'm not going to intruduce any extra dependencies.

**Comment by razonyang** [comment]
@LITUATUI I've implemented a simple solution for this, but naming is difficult, I'd name the module as `sticky-till-the-end` if no further suggestions, let me know if you have any ideas of naming.

Will release the module in those two days.

**Comment by LITUATUI** [comment]
Thanks @razonyang. That name works for me, it's clear in what it does.

**Comment by razonyang** [comment]
Preview:

https://github.com/hbstack/theme-cards/assets/17720932/80fa7535-a3f9-4dd7-9c8d-159824c596c3

To achieve this, you'd need to import `github.com/hbstack/blog/modules/sticky-till-the-end` and `github.com/hbstack/docs/modules/sticky-till-the-end` for `blog` and `docs` layout respectively.

I'm closing this now, please open another issue if there is a bug.

**Comment by razonyang** [comment]
Please put those modules under `theme-cards` module, otherwise cards theme will be overridden.
